ALTER TABLE companies ADD COLUMN IF NOT EXISTS telegram TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS working_hours TEXT;

ALTER TABLE property_drafts
ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES companies(id) ON DELETE CASCADE;
